package(default_visibility = ["//:__subpackages__"])

alias(
    name = "ar_actions",
    actual = select({
        "//:latest": "//clang/19.1.7:ar_actions",
        "//:19.1.7": "//clang/19.1.7:ar_actions",
    })
)
alias(
    name = "assembly_actions",
    actual = select({
        "//:latest": "//clang/19.1.7:assembly_actions",
        "//:19.1.7": "//clang/19.1.7:assembly_actions",
    })
)
alias(
    name = "c_compile",
    actual = select({
        "//:latest": "//clang/19.1.7:c_compile",
        "//:19.1.7": "//clang/19.1.7:c_compile",
    })
)
alias(
    name = "cpp_compile_actions",
    actual = select({
        "//:latest": "//clang/19.1.7:cpp_compile_actions",
        "//:19.1.7": "//clang/19.1.7:cpp_compile_actions",
    })
)
alias(
    name = "link_actions",
    actual = select({
        "//:latest": "//clang/19.1.7:link_actions",
        "//:19.1.7": "//clang/19.1.7:link_actions",
    })
)
alias(
    name = "link_data",
    actual = select({
        "//:latest": "//clang/19.1.7:link_data",
        "//:19.1.7": "//clang/19.1.7:link_data",
    })
)
alias(
    name = "objcopy_embed_data",
    actual = select({
        "//:latest": "//clang/19.1.7:objcopy_embed_data",
        "//:19.1.7": "//clang/19.1.7:objcopy_embed_data",
    })
)
alias(
    name = "strip",
    actual = select({
        "//:latest": "//clang/19.1.7:strip",
        "//:19.1.7": "//clang/19.1.7:strip",
    })
)
