package(default_visibility = ["//visibility:public"])

constraint_setting(
    name = "c++",
    default_constraint_value = "libc++",
)

constraint_value(
    name = "libc++",
    constraint_setting = ":c++",
)

constraint_value(
    name = "libstdc++",
    constraint_setting = ":c++",
)
