name: Bazel Hello World

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: build examples
      run: |
        cd examples/hello_world
        bazel build //...

        bazel build --@toolchains_cc//:use_runtimes=musl-static,libcxx-static --copt="-v" :hello
        bazel build --@toolchains_cc//:use_runtimes=glibc --copt="-v" :hello
