name: Bazel Hello World

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: build examples
      run: |
        cd examples/hello_world
        bazel build //...

        bazel build --@toolchains_cc//:use_runtimes=musl-static,libcxx-static //...
        bazel build --@toolchains_cc//:use_runtimes=glibc,libstdcxx,linux-libc-dev //...

  run-aarch64-windows:
    runs-on: windows-11-arm
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run Bazel on aarch64
      run: |
        cd examples/hello_world
        bazel run --@toolchains_cc//:use_runtimes=ucrt-static,msvc-static :hello
